### ISSUE TITLE
Esp32 CAM

### ISSUE THREAD

**Issue by oleksandr007** [ayushsharma82/AsyncElegantOTA#69] opened 2021-08-28 02:26 UTC
Reach until 11% and then reboot.

**Comment by ayushsharma82** [comment] 2021-08-28 02:48
Hi,
Please always refer to closed issues first.
This one has the solution for you: #39

Closing due to duplicate of #39 

Regards,
Ayush

**Closed by ayushsharma82** 2021-08-28 02:48 UTC
